version: "3"
services:
  nextjs:
    build: ./frontend
    ports:
      - "3000:3000"
  express:
    build: ./backend
    ports:
      - "4003:4003"
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bank_site_mysql
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
